### ISSUE TITLE
Error Installing paystack on Erpnext Version-14

### ISSUE THREAD

**Issue by ravi854** [mymi14s/frappe_paystack#2]
![paystack1](https://user-images.githubusercontent.com/85276497/220833318-c13deead-c154-4ca5-8aed-0550c52f855f.png)
![paystack2](https://user-images.githubusercontent.com/85276497/220833489-108acf9f-9e21-4027-8063-57aa02baac6a.png)

**Comment by brosboss** [comment]
I have solved this problem and sent a pull request accordingly "https://github.com/mymi14s/frappe_paystack/pull/3" 

The problem was with the "create_payment_gateway" in "/home/harry2/frappe_paystack/frappe_paystack/frappe_paystack/doctype/paystack_settings/paystack_settings.py".

While the "create_payment_gateway" method has been moved to "payments.utils" it was still called from "frappe.integrations.utils" hence the error. However, this has been modified in my pull request and hopefully, it would be accepted and merged. Thank you.

**Comment by mymi14s** [comment]
Version-14 release is now available.
